import type { FertilizerSeason, SunExposure } from '@/lib/plant-types';

export const DESERT_PLANT_CATEGORIES = [
  'Vegetables',
  'Herbs',
  'Natives/Cacti',
  'Trees/Shrubs',
  'Flowers',
] as const;

export type DesertPlantCategory = (typeof DESERT_PLANT_CATEGORIES)[number];

export type DesertPlantPreset = {
  id: string;
  category: DesertPlantCategory;
  name: string;
  species: string;
  container_type: string;
  pot_size: string;
  sun_exposure: SunExposure;
  watering_frequency_days: number;
  fertilizer_frequency_days: number;
  fertilizer_seasons: FertilizerSeason[];
  fertilizer_notes: string;
  location_in_garden: string;
  phoenix_notes: string;
};

export const desertPlantPresets: DesertPlantPreset[] = [
  {
    id: 'armenian-cucumber',
    category: 'Vegetables',
    name: 'Armenian Cucumber',
    species: 'Cucumis melo var. flexuosus',
    container_type: 'Grow Bag',
    pot_size: '20 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 2,
    fertilizer_frequency_days: 21,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Feed lightly every 2-3 weeks; increase watering during heat waves.',
    location_in_garden: 'Morning sun, light afternoon shade',
    phoenix_notes: 'Handles Phoenix heat better than standard cucumbers; use trellis and mulch.',
  },
  {
    id: 'cherry-tomato-heat-tolerant',
    category: 'Vegetables',
    name: 'Cherry Tomato (Heat Tolerant)',
    species: 'Solanum lycopersicum',
    container_type: 'Grow Bag',
    pot_size: '20 gallon',
    sun_exposure: 'partial_sun',
    watering_frequency_days: 2,
    fertilizer_frequency_days: 14,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Balanced fertilizer every 2 weeks while fruiting; avoid excess nitrogen.',
    location_in_garden: 'East side, protected from late-day heat',
    phoenix_notes: 'Spring and fall are strongest production windows in the Valley.',
  },
  {
    id: 'jalapeno-pepper',
    category: 'Vegetables',
    name: 'Jalapeno Pepper',
    species: 'Capsicum annuum',
    container_type: 'Grow Bag',
    pot_size: '10 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 3,
    fertilizer_frequency_days: 21,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Feed every 3 weeks; reduce nitrogen once flowering starts.',
    location_in_garden: 'Full sun with reflective heat protection',
    phoenix_notes: 'Thrives in Phoenix warmth; monitor daily in monsoon humidity spikes.',
  },
  {
    id: 'eggplant-ichiban',
    category: 'Vegetables',
    name: 'Eggplant',
    species: 'Solanum melongena',
    container_type: 'Grow Bag',
    pot_size: '15 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 2,
    fertilizer_frequency_days: 21,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Use compost tea or balanced liquid feed every 3 weeks.',
    location_in_garden: 'Open sun, mulch root zone',
    phoenix_notes: 'Heat loving crop that performs well through long Phoenix summers.',
  },
  {
    id: 'okra',
    category: 'Vegetables',
    name: 'Okra',
    species: 'Abelmoschus esculentus',
    container_type: 'Grow Bag',
    pot_size: '20 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 3,
    fertilizer_frequency_days: 30,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Light monthly feeding is enough in amended soil.',
    location_in_garden: 'Hottest full-sun zone',
    phoenix_notes: 'Excellent summer producer in Phoenix; harvest pods while tender.',
  },
  {
    id: 'swiss-chard',
    category: 'Vegetables',
    name: 'Swiss Chard',
    species: 'Beta vulgaris subsp. vulgaris',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'partial_sun',
    watering_frequency_days: 2,
    fertilizer_frequency_days: 30,
    fertilizer_seasons: ['fall', 'winter', 'spring'],
    fertilizer_notes: 'Monthly mild feed keeps leaves productive through cool months.',
    location_in_garden: 'Winter sun, summer shade cloth',
    phoenix_notes: 'Great cool-season leafy green for Phoenix fall through spring.',
  },
  {
    id: 'thai-basil',
    category: 'Herbs',
    name: 'Thai Basil',
    species: 'Ocimum basilicum var. thyrsiflora',
    container_type: 'Pot',
    pot_size: '5 gallon',
    sun_exposure: 'partial_sun',
    watering_frequency_days: 2,
    fertilizer_frequency_days: 21,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Half-strength liquid feed every 2-3 weeks.',
    location_in_garden: 'Morning sun with afternoon shade',
    phoenix_notes: 'Pinch flowers often; afternoon shade improves summer longevity.',
  },
  {
    id: 'rosemary',
    category: 'Herbs',
    name: 'Rosemary',
    species: 'Salvia rosmarinus',
    container_type: 'Pot',
    pot_size: '10 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 7,
    fertilizer_frequency_days: 60,
    fertilizer_seasons: ['spring', 'fall'],
    fertilizer_notes: 'Very light feeding only; overfertilizing reduces flavor and resilience.',
    location_in_garden: 'Southwest corner with strong drainage',
    phoenix_notes: 'Needs excellent drainage in alkaline soil; avoid constantly wet roots.',
  },
  {
    id: 'oregano',
    category: 'Herbs',
    name: 'Oregano',
    species: 'Origanum vulgare',
    container_type: 'Pot',
    pot_size: '5 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 5,
    fertilizer_frequency_days: 45,
    fertilizer_seasons: ['spring', 'fall'],
    fertilizer_notes: 'Minimal feeding; too much fertilizer weakens aroma.',
    location_in_garden: 'Bright spot, no reflected heat wall',
    phoenix_notes: 'Performs best in shoulder seasons; trim regularly for dense growth.',
  },
  {
    id: 'mexican-tarragon',
    category: 'Herbs',
    name: 'Mexican Tarragon',
    species: 'Tagetes lucida',
    container_type: 'Pot',
    pot_size: '10 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 4,
    fertilizer_frequency_days: 45,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Monthly to bi-monthly light feed supports flowering and flavor.',
    location_in_garden: 'Hot bed edge with airflow',
    phoenix_notes: 'Excellent heat-tolerant herb substitute for French tarragon in Phoenix.',
  },
  {
    id: 'garlic-chives',
    category: 'Herbs',
    name: 'Garlic Chives',
    species: 'Allium tuberosum',
    container_type: 'Pot',
    pot_size: '5 gallon',
    sun_exposure: 'partial_sun',
    watering_frequency_days: 3,
    fertilizer_frequency_days: 30,
    fertilizer_seasons: ['spring', 'fall'],
    fertilizer_notes: 'Light monthly feeding during active growth.',
    location_in_garden: 'Filtered light near patio',
    phoenix_notes: 'Handles heat better than common chives with partial afternoon shade.',
  },
  {
    id: 'saguaro-cactus',
    category: 'Natives/Cacti',
    name: 'Saguaro Cactus',
    species: 'Carnegiea gigantea',
    container_type: 'Pot',
    pot_size: '10 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 21,
    fertilizer_frequency_days: 90,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Cactus fertilizer at quarter strength in warm months only.',
    location_in_garden: 'Open desert bed, no irrigation overspray',
    phoenix_notes: 'Avoid winter watering and keep crown dry during cool periods.',
  },
  {
    id: 'prickly-pear',
    category: 'Natives/Cacti',
    name: 'Prickly Pear',
    species: 'Opuntia spp.',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 14,
    fertilizer_frequency_days: 90,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Optional low-nitrogen cactus feed once or twice per warm season.',
    location_in_garden: 'Desert edge with gravel mulch',
    phoenix_notes: 'Monsoon rain is often enough; reduce supplemental irrigation accordingly.',
  },
  {
    id: 'golden-barrel',
    category: 'Natives/Cacti',
    name: 'Golden Barrel Cactus',
    species: 'Echinocactus grusonii',
    container_type: 'Pot',
    pot_size: '10 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 18,
    fertilizer_frequency_days: 120,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Single spring feeding is usually sufficient.',
    location_in_garden: 'High-heat focal point with fast drainage',
    phoenix_notes: 'Protect from prolonged winter cold and avoid standing water.',
  },
  {
    id: 'parrys-agave',
    category: 'Natives/Cacti',
    name: "Parry's Agave",
    species: 'Agave parryi',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 14,
    fertilizer_frequency_days: 120,
    fertilizer_seasons: ['spring'],
    fertilizer_notes: 'Usually no fertilizer needed; use compost top-dress only if needed.',
    location_in_garden: 'Rocky bed with slope',
    phoenix_notes: 'Cold tolerant agave with excellent drought performance in Phoenix landscapes.',
  },
  {
    id: 'desert-milkweed',
    category: 'Natives/Cacti',
    name: 'Desert Milkweed',
    species: 'Asclepias subulata',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 10,
    fertilizer_frequency_days: 120,
    fertilizer_seasons: ['spring'],
    fertilizer_notes: 'No regular fertilizer needed once established.',
    location_in_garden: 'Pollinator strip, full sun',
    phoenix_notes: 'Host plant for monarchs; cut back lightly after frost damage.',
  },
  {
    id: 'texas-sage',
    category: 'Trees/Shrubs',
    name: 'Texas Sage',
    species: 'Leucophyllum frutescens',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 7,
    fertilizer_frequency_days: 90,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Light spring feed only if growth is weak.',
    location_in_garden: 'West exposure hedge line',
    phoenix_notes: 'Blooms after humidity rises; avoid overwatering to prevent legginess.',
  },
  {
    id: 'yellow-bells',
    category: 'Trees/Shrubs',
    name: 'Yellow Bells',
    species: 'Tecoma stans',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 5,
    fertilizer_frequency_days: 60,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Balanced feed every 2 months during bloom season.',
    location_in_garden: 'South wall heat island',
    phoenix_notes: 'Fast grower in desert heat; prune after bloom flushes for shape.',
  },
  {
    id: 'pomegranate',
    category: 'Trees/Shrubs',
    name: 'Pomegranate',
    species: 'Punica granatum',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 5,
    fertilizer_frequency_days: 45,
    fertilizer_seasons: ['spring', 'summer'],
    fertilizer_notes: 'Citrus/fruit tree fertilizer every 6 weeks during active growth.',
    location_in_garden: 'Full sun with deep soak zone',
    phoenix_notes: 'Heat tolerant fruiting shrub/tree; deep, infrequent watering improves resilience.',
  },
  {
    id: 'meyer-lemon',
    category: 'Trees/Shrubs',
    name: 'Meyer Lemon',
    species: 'Citrus x meyeri',
    container_type: 'Pot',
    pot_size: '20 gallon',
    sun_exposure: 'partial_sun',
    watering_frequency_days: 3,
    fertilizer_frequency_days: 30,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Citrus-specific fertilizer monthly in warm season.',
    location_in_garden: 'Morning sun, protected from reflected afternoon heat',
    phoenix_notes: 'Protect from hard frost and intense west-wall summer reflection.',
  },
  {
    id: 'desert-willow',
    category: 'Trees/Shrubs',
    name: 'Desert Willow',
    species: 'Chilopsis linearis',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 10,
    fertilizer_frequency_days: 120,
    fertilizer_seasons: ['spring'],
    fertilizer_notes: 'Rarely needs feeding; one spring compost feed is enough.',
    location_in_garden: 'Low-water xeriscape zone',
    phoenix_notes: 'Native-adapted tree for low-water landscapes; avoid constant shallow irrigation.',
  },
  {
    id: 'lantana',
    category: 'Flowers',
    name: 'Lantana',
    species: 'Lantana camara',
    container_type: 'Pot',
    pot_size: '10 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 4,
    fertilizer_frequency_days: 60,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Light feeding every 2 months to sustain blooms.',
    location_in_garden: 'Pollinator container by walkway',
    phoenix_notes: 'Reliable Phoenix heat bloomer; trim back hard in late winter.',
  },
  {
    id: 'desert-marigold',
    category: 'Flowers',
    name: 'Desert Marigold',
    species: 'Baileya multiradiata',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 8,
    fertilizer_frequency_days: 120,
    fertilizer_seasons: ['spring'],
    fertilizer_notes: 'Generally no fertilizer required in native soil conditions.',
    location_in_garden: 'Desert border with gravel mulch',
    phoenix_notes: 'Native wildflower that thrives with low water and strong sun.',
  },
  {
    id: 'firecracker-penstemon',
    category: 'Flowers',
    name: 'Firecracker Penstemon',
    species: 'Penstemon eatonii',
    container_type: 'Raised Bed',
    pot_size: 'Large',
    sun_exposure: 'full_sun',
    watering_frequency_days: 7,
    fertilizer_frequency_days: 90,
    fertilizer_seasons: ['fall', 'winter', 'spring'],
    fertilizer_notes: 'Light compost application in fall supports cool-season bloom.',
    location_in_garden: 'Winter sun pollinator strip',
    phoenix_notes: 'Excellent hummingbird plant for Phoenix cool season.',
  },
  {
    id: 'blanket-flower',
    category: 'Flowers',
    name: 'Blanket Flower',
    species: 'Gaillardia pulchella',
    container_type: 'Pot',
    pot_size: '5 gallon',
    sun_exposure: 'full_sun',
    watering_frequency_days: 6,
    fertilizer_frequency_days: 90,
    fertilizer_seasons: ['spring', 'summer', 'fall'],
    fertilizer_notes: 'Very light feeding to avoid excessive foliage.',
    location_in_garden: 'Sunny front container',
    phoenix_notes: 'Heat and drought tolerant color; deadhead to extend bloom cycles.',
  },
];
